#' Simulated partially paired counts from three sites
#'
#' @description
#' A simulated dataset in which source 2 recorded a count on every unit and
#' source 1 on a random 20% of units in each site. It is generated from the
#' model of [binegbin_partialobs()] with site effects on congruence and bias,
#' so every example can be run, and its estimates compared with known values.
#' The latent components behind each pair are in [bicount_sim_latent].
#'
#' @format A data frame with 540 rows (three sites of 180 units) and 5 columns:
#' \describe{
#'   \item{site}{Factor, `A`, `B` or `C`.}
#'   \item{unit}{Integer, the unit within its site, 1 to 180.}
#'   \item{y1}{Integer, the count recorded by source 1; `NA` where source 1 did
#'     not record the unit.}
#'   \item{y2}{Integer, the count recorded by source 2, on every unit.}
#'   \item{y1_obs}{Integer, 1 where `y1` was recorded and 0 where it was not.}
#' }
#'
#' @details
#' Each unit's counts were constructed by trivariate reduction,
#' `y1 = Ns + N1` and `y2 = Ns + N2`, from three independent negative-binomial
#' components with means `mu = M f`, `lambda1 = M (1 - f)(1 + beta)` and
#' `lambda2 = M (1 - f)(1 - beta)`, and dispersions `phi = 1 / kappa^2`. Here `M`
#' is the midpoint of the two expected counts, `f` the congruence, and
#' `beta = tanh(delta)` the bounded source bias. The generating values were:
#'
#' | site | M | f | beta | kappas | kappax1 | kappax2 |
#' |---|---|---|---|---|---|---|
#' | A | 5 | 0.5 | 0 | 0.5 | 0.5 | 0.5 |
#' | B | 5 | 0.7 | 0.3 | 0.5 | 0.5 | 0.5 |
#' | C | 5 | 0.9 | -0.3 | 0.5 | 0.5 | 0.5 |
#'
#' Source 1 was recorded on exactly 36 units per site, drawn at random within
#' site, so whether `y1` was recorded does not depend on either count.
#' Generated by `data-raw/bicount_sim.R` in the package source, with
#' `set.seed(20261002)`.
#'
#' Before fitting with [binegbin_partialobs()], replace the `NA` in `y1` with a
#' placeholder such as 0: brms drops rows with a missing response, which would
#' discard the observed `y2` on those rows. The likelihood does not read `y1`
#' where `y1_obs` is 0.
#'
#' @seealso [bicount_sim_latent], [binegbin_partialobs()],
#'   [binegbin_mfd_to_dpars()]
#'
#' @examples
#' str(bicount_sim)
#' table(bicount_sim$site, bicount_sim$y1_obs)
#'
#' # Every recorded pair is the sum of its latent components
#' rec <- bicount_sim$y1_obs == 1
#' all(bicount_sim$y1[rec] ==
#'       bicount_sim_latent$Ns[rec] + bicount_sim_latent$N1[rec])
#'
#' \dontrun{
#' # Fitting compiles a Stan model and samples, which takes minutes.
#' # The model is written in midpoint M, congruence f and bias delta through
#' # non-linear formulas, with eta = log M, con = logit f, methd = delta and
#' # the three dispersions on the kappa scale, and site effects on f and delta.
#' library(brms)
#' dat <- bicount_sim
#' dat$y1[dat$y1_obs == 0] <- 0L
#'
#' fit <- brm(
#'   bf(y1 | vint(y2, y1_obs) ~ 1, nl = TRUE) +
#'     nlf(mu        ~ eta + log_inv_logit(con)) +
#'     nlf(lambdaone ~ log(2) + eta + log_inv_logit(-con) +
#'                     log_inv_logit(2 * methd)) +
#'     nlf(lambdatwo ~ log(2) + eta + log_inv_logit(-con) +
#'                     log_inv_logit(-2 * methd)) +
#'     nlf(shapes    ~ log(1 / kappas^2)) +
#'     nlf(shapexone ~ log(1 / kappaxone^2)) +
#'     nlf(shapextwo ~ log(1 / kappaxtwo^2)) +
#'     lf(eta ~ 1) + lf(con ~ 0 + site) + lf(methd ~ 0 + site) +
#'     lf(kappas ~ 1) + lf(kappaxone ~ 1) + lf(kappaxtwo ~ 1),
#'   data     = dat,
#'   family   = binegbin_partialobs(),
#'   stanvars = binegbin_partialobs_stanvars(),
#'   prior    = c(
#'     set_prior("normal(0.5, 2)", class = "b", nlpar = "eta"),
#'     set_prior("normal(0, 1.5)", class = "b", nlpar = "con"),
#'     set_prior("normal(0, 0.5)", class = "b", nlpar = "methd"),
#'     set_prior("normal(0, 1)",   class = "b", nlpar = "kappas",    lb = 0),
#'     set_prior("normal(0, 1)",   class = "b", nlpar = "kappaxone", lb = 0),
#'     set_prior("normal(0, 1)",   class = "b", nlpar = "kappaxtwo", lb = 0)
#'   ),
#'   chains = 4, cores = 4, seed = 1
#' )
#'
#' # Congruence by site, against 0.5, 0.7 and 0.9
#' cols <- c("Estimate", "Q2.5", "Q97.5")
#' plogis(fixef(fit)[c("con_siteA", "con_siteB", "con_siteC"), cols])
#' # Bias beta = tanh(delta) by site, against 0, 0.3 and -0.3
#' tanh(fixef(fit)[c("methd_siteA", "methd_siteB", "methd_siteC"), cols])
#'
#' # The unrecorded source-1 counts, drawn conditionally on each unit's y2
#' y1_draws <- posterior_predict(fit)[, dat$y1_obs == 0]
#' }
"bicount_sim"

#' Latent components of the simulated partially paired counts
#'
#' @description
#' The three latent components behind each pair of counts in [bicount_sim]:
#' the count recorded by both sources and the counts recorded by each source
#' alone. Kept apart from [bicount_sim] because they would not be observed in
#' practice; they give the true value of every count, including the source-1
#' counts that were not recorded, against which estimates and predictions can
#' be checked.
#'
#' @format A data frame with 540 rows, aligned row for row with
#'   [bicount_sim], and 5 columns:
#' \describe{
#'   \item{site, unit}{As in [bicount_sim].}
#'   \item{Ns}{Integer, the count recorded by both sources.}
#'   \item{N1}{Integer, the count recorded by source 1 only.}
#'   \item{N2}{Integer, the count recorded by source 2 only.}
#' }
#'
#' @details `y1 = Ns + N1` on every unit, recorded or not, and `y2 = Ns + N2`.
#'   Generating values and seed are given in [bicount_sim].
#'
#' @seealso [bicount_sim]
#'
#' @examples
#' # The true source-1 total over the units on which source 1 was not recorded
#' un <- bicount_sim$y1_obs == 0
#' tapply(bicount_sim_latent$Ns[un] + bicount_sim_latent$N1[un],
#'        bicount_sim$site[un], sum)
"bicount_sim_latent"
